let tech_suggestions = [
    { id: 1, name: "MongoDB" },
    { id: 2, name: "Express" },
    { id: 3, name: "React" },
    { id: 4, name: "Node.js" },
    { id: 5, name: "Python" },
    { id: 6, name: "JavaScript" },
    { id: 7, name: "Java" },
    { id: 8, name: "C++" },
    { id: 9, name: "C#" },
    { id: 10, name: "HTML/CSS" },
    { id: 11, name: "Swift" },
    { id: 12, name: "SQL" },
    { id: 13, name: "Ruby" },
    { id: 14, name: "Scala" },
    { id: 15, name: "Lisp" },
    { id: 16, name: "Angular" },
    { id: 17, name: "VueJS" },
    { id: 18, name: "Flutter" },
    { id: 19, name: "Kubernetes" },
    { id: 20, name: "Jupyter" },
    { id: 21, name: "Pytorch" },
    { id: 22, name: "Numpy" },
    { id: 23, name: "Passport" },
    { id: 24, name: "Kotlin" },
    { id: 25, name: "JQuery" },
    { id: 26, name: "Rust" },
    { id: 27, name: "WebAssembly" },
    { id: 28, name: "TypeScript" },
    { id: 29, name: "Go" },
    { id: 30, name: "PHP" },
    { id: 31, name: "Assembly" },
    { id: 32, name: "VBA" },
    { id: 33, name: ".NET" },
    { id: 34, name: "SQL" },
    { id: 35, name: "Jenkins" },
    { id: 36, name: "GraphQL" },
    { id: 37, name: "Firebase" },
    { id: 38, name: "Azure" },
    { id: 39, name: "AWS" },
    { id: 40, name: "GCP" }
];

module.exports = tech_suggestions;