let techSuggestions = {
    "MongoDB": 1,
    "Express": 2,
    "React": 3,
    "Node.js": 4,
    "Python": 5,
    "JavaScript": 6,
    "Java": 7,
    "C++": 8,
    "C#": 9,
    "HTML/CSS": 10,
    "Swift": 11,
    "SQL": 12,
    "Ruby": 13,
    "Scala": 14,
    "Lisp": 15,
    "Angular": 16,
    "VueJS": 17,
    "Flutter": 18,
    "Kubernetes": 19,
    "Jupyter": 20,
    "Pytorch": 21,
    "Numpy": 22,
    "Passport": 23,
    "Kotlin": 24,
    "JQuery": 25,
    "Rust": 26,
    "WebAssembly": 27,
    "TypeScript": 28,
    "Go": 29,
    "PHP": 30,
    "Assembly": 31,
    "VBA": 32,
    ".NET": 33,
    "SQL": 34,
    "Jenkins": 35,
    "GraphQL": 36,
    "Firebase": 37,
    "Azure": 38,
    "AWS": 39,
    "GCP": 40
}

module.exports = techSuggestions;